stages:
        - build
        - run

build-maven:
        stage: build
        script: ./build.sh
        script: 'mv target build'

run-packatt:
        stage: run
        script: java -jar ./target/pakcatt-0.1.jar --spring.config.location=/opt/pakcatt/application.properties
