stages:
        - build
        - run

artifacts:
        paths:
                - target/*.jar
        expire_in: 1 day

build-maven:
        stage: build
        script: ./build.sh

run-packatt:
        stage: run
        script: java -jar ./docker/pakcatt-0.1.jar --spring.config.location=/opt/pakcatt/application.properties
