stages:
        - build
        - deploy
        - restart

build-maven:
        stage: build
        script: mvn clean install
        artifacts:
            paths:
                - target/*.jar
            expire_in: 1 day
        only:
                - main

deploy-packatt:
        stage: deploy
        script:
          - rm /opt/pakcatt/pakcatt-0.1.jar
          - cp ./target/pakcatt-0.1.jar /opt/pakcatt/
        only:
                - main

run-packatt:
        stage: restart
        script: service pakcatt restart
        only:
                - main
