stages:
        - build
        - deploy
        - restart

build-maven:
        stage: build
        script: /usr/bin/mvn clean install
        artifacts:
          paths:
            - target/*.jar
          expire_in: 1 day
        only:
          - main

deploy-packatt:
        stage: deploy
        script:
          - /usr/bin/rm /opt/pakcatt/pakcatt-0.1.jar
          - /usr/bin/cp ./target/pakcatt-0.1.jar /opt/pakcatt/
          - /usr/bin/chmod 750 /opt/pakcatt/pakcatt-0.1.jar
        only:
          - main

run-packatt:
        stage: restart
        script: /usr/bin/sudo /usr/sbin/service pakcatt restart
        only:
          - main
