## Feature configuration
# Your callsign-SSID. Connections to this callsign will be accepted.
pakcatt:
  application:
    mycall: PAKCAT-1
    beacon:
      message: PAKCAT-1 on frequency, running PakCatt. Connect to PAKCAT-1 to try it out.
      interval_minutes: 0 # An interval of 0 disables beaconing.
      destination: CQ # The destination address for beacon messages. This is typically 'CQ'

    scriptable:
      workingDir: ./
      timeout: 60 # Time allowed for scripts to run
      scripts:
        - name: 'Example Date'
          pathConnect: 'scripts/example_date_connect.sh'
          pathRequest: 'scripts/example_date_request.sh'
#       This script is an example that sends messages to stations that beacon from pre-defined locations
#       See location_messages_wrapper.sh and location_messages.kts
#        - name: 'Location messages'
#          pathConnect: 'scripts/location_messages_wrapper.sh'
#          pathRequest: 'scripts/location_messages_wrapper.sh'

  ## Serial port / TNC configuration
  serial-port-path: /dev/<YOUR TNC SERIAL PATH>
  serial-port-baud: 9600

  ## Packet performance parameters
  network.packet:
    frame_size_max: 128 The maximum number of bytes send in each frame
    frames_per_over: 4 # The maximum number of frames / packets sent in each transmission
    minTXPauseSeconds: 2 # The minimum amount of time left between transmissions
    deliveryRetryTimeSeconds: 10 # The time between re-sending frames that have not been acknowledged
    maxDeliveryAttempts: 10 # The number of times a frame is re-sent if not acknowledged


spring:
  ## Database configuration
  data.mongodb.database: pakcatt
  #spring.data.mongodb.host: 127.0.0.1
  #spring.data.mongodb.port: 27017

  ## TCP/IP server
  #server.address=127.0.0.1
  server.port: 8080

  freemarker.template-loader-path: classpath:/templates/
  freemarker.suffix: .ftl
  profiles.active: production


## Logging and development parameters
logging:
  pattern.console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%18.18logger{0}]){blue} %clr(${LOG_LEVEL_PATTERN:\t%5p:}) %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level.pakcatt: info
